### ISSUE TITLE
unable to connect to tembo epp client

### ISSUE THREAD

**Issue by anantsparrow** [getnamingo/registry#101]
hey there, kindly help us to resolve this issues

**Comment by anantsparrow** [comment]
http://sparrow.pw/tembo/examples/DomainCheck.php

Deprecated: Creation of dynamic property Pinga\Tembo\Epp::$responseLogger is deprecated in /www/wwwroot/sparrow.pw/vendor/pinga/tembo/src/Epp.php on line 32

Deprecated: Creation of dynamic property Pinga\Tembo\Epp::$requestLogger is deprecated in /www/wwwroot/sparrow.pw/vendor/pinga/tembo/src/Epp.php on line 33

Deprecated: Creation of dynamic property Pinga\Tembo\Epp::$commonLogger is deprecated in /www/wwwroot/sparrow.pw/vendor/pinga/tembo/src/Epp.php on line 34
Error : The stream or file "/www/wwwroot/sparrow.pw/vendor/pinga/tembo/src/../log/response-2024-06-17.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: Namingo EPP Server 1.0 2024-06-17T15:21:55.644Z 1.0 en urn:ietf:params:xml:ns:domain-1.0 urn:ietf:params:xml:ns:contact-1.0 urn:ietf:params:xml:ns:host-1.0 https://namingo.org/epp/funds-1.0 https://namingo.org/epp/identica-1.0 urn:ietf:params:xml:ns:secDNS-1.1 urn:ietf:params:xml:ns:rgp-1.0 urn:ietf:params:xml:ns:launch-1.0 urn:ietf:params:xml:ns:idn-1.0 urn:ietf:params:xml:ns:epp:fee-1.0 urn:ar:params:xml:ns:price-1.1 Error : Call to a member function domainCheck() on null

**Comment by anantsparrow** [comment]
also, please update the whmcs rfc epp module to work properly with namingo, as it does not create new contacts

**Comment by getpinga** [comment]
Closing as the relevang issues will be addressed in the WHMCS module or Tembo issues.
