### ISSUE TITLE
after migration web ui of whois is not working

### ISSUE THREAD

**Issue by anantsparrow** [getnamingo/registry#124]
Hey there, we did a domain migration of main domain for registry panel, but seems like except the web ui of whois.sparrowhost.net

everything is working fine, however the port etc everything seems fine, can you suggest some fixes?

**Comment by getpinga** [comment]
Check your config file for the web whois (/opt/registry/whois/web/config.php) if the hostnames for whois and rdap there match the hostnames you use.

**Comment by anantsparrow** [comment]
Thank you it is fixed.
