### ISSUE TITLE
Error  at CustomizationMiddleware.php Namingo registry side

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#169]
Error when  testing with namingo registrar on Namingo registry side ofcourse domains doesn't register due to this error

error  Namingo registry side 
[2024-09-16T21:16:51.594156+00:00] errors.WARNING: E_WARNING: Closure::{closure}(): Argument # 3 ($response) must be passed by reference, value given {"code":2,"message":"Closure::{closure}(): Argument # 3 ($response) must be passed by reference, value given","file":"/var/www/cp/vendor/mevdschee/php-crud-api/src/Tqdev/PhpCrudApi/Middleware/CustomizationMiddleware.php","line":38} []

**Comment by getpinga** [comment]
Could you please clarify? The Namingo Registrar uses EPP protocol and this error comes from the control panel so it is unlikely to be related.

**Comment by wvro-org** [comment]
Yes it's smth related to  Namingo Registry control panel when clicking on any menu button it gives this errors
I suppose it's need to be fixed (not urgent)

**Comment by getpinga** [comment]
What do you have for value of APP_ENV in /var/www/cp/.env?
Also what Ubuntu do you use?

**Comment by wvro-org** [comment]
APP_ENV=public

**Comment by wvro-org** [comment]
not urgent... not closing... will'get back later

**Comment by getpinga** [comment]
It will be fixed in the next version, I found an easy way.

**Comment by getpinga** [comment]
https://github.com/getnamingo/registry/commit/0c2a0afb05476c8ce8402f6d9e5f544a36d7370b
Try this

**Comment by getpinga** [comment]
Closing as no feedback, and I've stopped seeing the error after the september update.
