### ISSUE TITLE
Make Namingo compatible? Universal Acceptance

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#172]
Make Namingo compatible?.... Universal Acceptance
for maybe v 1.0.5/ 1.0.6
No more words nedeed....

**Comment by getpinga** [comment]
Fixed in https://github.com/getnamingo/registry/commit/4fa128933409cbeed3397481747b7bc8f5931566 and next.

**Comment by wvro-org** [comment]
Reopened as still need to implement on namingo it's self.... to accept likes of  too...
test@テス.test  seems ✔
テス@テス.テスト seems ✖

**Comment by getpinga** [comment]
Yes, unfortunately the html email input is not UA ready, I've removed most but this one is still there. WIll fix.
