### ISSUE TITLE
Location of registry policy settings?

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#173]
whecn creating domain idn-test.idn-example.test (not actual domain) is not available: Invalid domain name format, please review registry policy about accepted labels

registry policy about accepted labels - location (tried my self haven't found either in files or cp )

**Comment by getpinga** [comment]
When you create a TLD via the panel, you will see option for `Supported Script`. It can not be changed later, if you need, let me know and give you how to change via DB.

**Comment by wvro-org** [comment]
figured it out...
SystemController.php lines  383-399

それを考え出した.test1jp = xn--r8j4aqk6tib7001cx78d.test1jp 
それを考え出した1.test1jp = xn--1-87tzbwam1yoby573cnuwe.test1jp ❌  as this IDN tables doesn't match numbers 


```php
            switch ($data['script']) {
                case 'ascii':
                    $idntable = '/^(?!-)(?!.*--)[A-Z0-9-]{1,63}(?<!-)(.(?!-)(?!.*--)[A-Z0-9-]{1,63}(?<!-))*$/i';
                    break;
                case 'cyrillic':
                    $idntable = '/^[а-яА-ЯґҐєЄіІїЇѝЍћЋљЈ]+$/u';
                    break;
                case 'japanese':
                    $idntable = '/^[ぁ-んァ-ン一-龯々]+$/u';
                    break;
                case 'korean':
                    $idntable = '/^[가-힣]+$/u';
                    break;
                default:
                    $idntable = '/^(?!-)(?!.*--)[A-Z0-9-]{1,63}(?<!-)(.(?!-)(?!.*--)[A-Z0-9-]{1,63}(?<!-))*$/i';
                    break;
            }

```

**Comment by getpinga** [comment]
Thank you , it is fixed now.
