### ISSUE TITLE
OpenDNSSEC  signes only one zone

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#176]
Using  origial write-zone.php DNSSEC with OpenDNSSEC:... only signes one zone
and ofcourse all zones added
ods-enforcer zone add -z test -p default -i /var/lib/bind/test.zone
and checked that they'are added
ods-enforcer zone list

zone "test." {
    type master;
    file "/var/lib/bind/test.zone.signed";
    allow-transfer { key "test.key"; };
    also-notify { <slave-server-IP>; };
};

zone "com.test." {
    type master;
    file "/var/lib/bind/com.test.zone.signed";
    allow-transfer { key "com.test.key"; };
    also-notify { <slave-server-IP>; };
};

-- only  example.test.  is signed....
zone "test.test." { 
    type master;
    file "/var/lib/bind/test.test.zone.signed";
    allow-transfer { key "test.test.key"; };
    also-notify { <slave-server-IP>; };
};

**Comment by wvro-org** [comment]
Fixed by specifying each command for each tld... in write-zone.php ... (#180)

**Comment by getpinga** [comment]
Reopened as still need to investigate.

**Comment by getpinga** [comment]
Fixed in 
ff871dd
