### ISSUE TITLE
Slim Application Error Message: The "map" filter expects a sequence/mapping or "Traversable", got "null".

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#177]
Slim Application Error
TLD .example setuped correctly 
1. created domain test1.example 
2. tryed to update https://example.com/domain/update/test1.example 
3. gives error Slim Application Error Message: The "map" filter expects a sequence/mapping or "Traversable", got "null".
4.figured out main cause is that db table domain_status isn't updated when creating domain 
5. temp fix -> create new entry in table  `domain_status`

**Comment by getpinga** [comment]
Fixed in current version.
