### ISSUE TITLE
Load fake tlds from config file

### ISSUE THREAD

**Issue by istiak101** [getnamingo/registry#33]
I don't get it why this should verify valid tlds from ICANN.

Anyway this should be loadable from config file rather than being hardcoded.
https://github.com/getnamingo/registry/blob/b4ccc2b0e8626cf605629dde456dac9c6baaceee/cp/bootstrap/helper.php#L285

**Comment by getpinga** [comment]
Thanks, good find. Will work on it.

**Comment by getpinga** [comment]
This has been now fixed. Please test and let me know if there are further issues.
