### ISSUE TITLE
issue with 3rd level domains

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#52]
Finally figured it out with 3rd level domains
---
default test TLDs
.TEST
.COM.TEST

tlds with db id
```
id     tld
 1    .TEST
 2   .COM.TEST
 4   .example.com
 5   .COM
 6  .example.org
```
when creating 3rd level domain nic.com.test registry puts it into .TEST tld not into .COM.TEST 
and for example.com when adding it  Registry -> TLDs menu and specifiing .example.com in .env file "TEST_TLDs
it dosn't work ... (when checking Domain nic.example.com  error= nic.example.com is not available: Zone is not supported)
so it requires to add .com TLD and when creating nic.example.com it adds it into .COM TLD not into .example.com too

<img width="111" alt="Screenshot 2023-12-30 at 11 51 21" src="https://github.com/getnamingo/registry/assets/66093777/76f57f71-aae4-4d97-a40a-9dfb33262502">
 
<img width="115" alt="Screenshot 2023-12-30 at 11 50 48" src="https://github.com/getnamingo/registry/assets/66093777/30c37f34-9339-4e2a-b9ec-e79ed63576ba">
<img width="172" alt="Screenshot 2023-12-30 at 12 14 06" src="https://github.com/getnamingo/registry/assets/66093777/050cee0a-a90f-49d3-8b30-7d471cfc10fa">
<img width="114" alt="Screenshot 2023-12-30 at 12 14 32" src="https://github.com/getnamingo/registry/assets/66093777/adc720fc-05a1-49c1-9f15-25005de66c45">

**Comment by getpinga** [comment]
Will reproduce and fix, thanks.

**Comment by getpinga** [comment]
Reproduced. Will work on it for the next few days.

**Comment by getpinga** [comment]
It was actually qute easy.  Replace cp/bootstrap/helper.php with the version from the last commit here and let me know if it got fixed.

**Comment by wvro-org** [comment]
CP works fine when cp/bootstrap/helper.php replaced with new....

**Comment by getpinga** [comment]
Great, thanks. Closing this as the code is the same for both, you will just need to clone the full EPP again.
