### ISSUE TITLE
Add 14.1 Setup Not Hidden Master DNS with BIND

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#59]
Add 14.1 Setup Not Hidden Master DNS with BIND

**Comment by getpinga** [comment]
Could you please clarify this? Not sure what do you mean - add instructions how to create a regular DNS server?

**Comment by wvro-org** [comment]
> Could you please clarify this? Not sure what do you mean - add instructions how to create a regular DNS server?

yes... f
