### ISSUE TITLE
Add currency setting to Registry Configuration 

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#64]
Add currency setting to  Registry Configuration ...
so the Financial Information would be in repspective currency
for example registry is based in Japan so all financial info in Japanese yen...

and for example if registrar is from UK they could select to Display their currency... aka add menu simmilar to Language Menu...

**Comment by getpinga** [comment]
I'll add the ability to choose the currency per registry soon and change it based on that, but for the registrar individually to select currency it will require currency exchange which unless you really need it for a project now, I'll postpone to v1.1

**Comment by getpinga** [comment]
Latest commit fixed this one in general.

Regarding registrars choosing also their own currency and currency exchange, I'll add to the todo list for 1.1
