### ISSUE TITLE
Always ASCII

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#73]
When creating NewTLD for .example and/or  test.example and selecting Supported Script other then ASCII for some reason system saves it with ASCII script supported... in DB tlds idn_table are indeed - ascii

**Comment by wvro-org** [comment]
to my mind the issue is in SystemController.php public function createTld it  always uses default idn table wich is ASCII
Lines 222-364

**Comment by wvro-org** [comment]
and for example when creating tld it allows to create both TDLS 
テスト | xn--zckzah 
<img width="1787" alt="Screenshot 2024-01-20 at 21 49 22" src="https://github.com/getnamingo/registry/assets/66093777/0c3cb58c-5937-4ec7-aeb8-6488395a3653">
and when trying to access setting of either tlds it displays red error "invalid tlds"

**Comment by getpinga** [comment]
This got fixed, please check and reopen if still having issues.
