### ISSUE TITLE
add support for nginx and apache

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/registry#76]
Add support to run namingo on nginx and apache webserver
and  add config  for nginx and apache

**Comment by wvro-org** [comment]
to clarify... I'm taking about using nginx/apache instead of caddy webserver... https://github.com/getnamingo/registry/blob/main/docs/install.md#6-configure-caddy-webserver

**Comment by getpinga** [comment]
Understood, thanks. Support is there - all should work without changes, will be able to provide some configuration files and mention in the installer docs. But for the automatic installer, maybe will leave it for v1.1 unless you need it now.

**Comment by wvro-org** [comment]
about apache2 ... figured out config and mananged at least get to "welcome page"
anfortunetly no further...  
here's config for apache2
```
<VirtualHost YOUR_IP:443>
    ServerName YOUR_DOMAIN
    DocumentRoot "/var/www/cp/public"
    ErrorLog "/var/log/apache2/error.log"
    CustomLog "/var/log/apache2/access.log" combined

    SSLEngine on
    SSLCertificateFile path_to_YOUR_DOMAIN_ssl_cert
    SSLCertificateKeyFile path_to_YOUR_DOMAIN_ssl_privkey
    SSLCertificateChainFile path_to_YOUR_DOMAIN_ssl_CA_chain.

    <Directory "/var/www/cp/public">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch "\.php$">
        SetHandler application/x-httpd-php
    </FilesMatch>

    <Location /adminer.php>
        Alias /usr/share/adminer
    </Location>
</VirtualHost>
```
